Readme Updates
upbound/configuration-azure-database pull request #20
Opened 2024-02-05 16:10 UTC by tr0njavolta

2024-02-14 23:40 UTC, ytsarev requested changes
thanks for the readme, left two suggestions

2024-02-14 23:40 UTC, ytsarev commented on crossplane.yaml
> +     For more details and customization options, you can explore [the GitHub repository](https://github.com/upbound/configuration-app).
```suggestion
     For more details and customization options, you can explore [the GitHub repository](https://github.com/upbound/configuration-azure-database).
```

2024-02-14 23:40 UTC, ytsarev commented on README.md
> +- **Composition of the Azure database resources:** Configured in [/apis/composition.yaml](/apis/composition.yaml), it provisions an Azure database and resources in the `upbound-system` namespace.
```suggestion
- **Composition of the Azure database resources:** Configured in [/apis/composition.yaml](/apis/composition.yaml), it provisions an Azure database and auxiliary managed resources.
```

2024-02-16 05:49 UTC, haarchri approved these changes

2024-02-16 05:50 UTC, merged